### ISSUE TITLE
CA for methods of Doctrine repositories

### ISSUE THREAD

**Issue by raziel057** [pulse00/Symfony-2-Eclipse-Plugin#257]
Hi,

I'm not sure if the current issue comes from PDT or Symfony eclipse plugin, but when I don't have the same propositions depending on the parameter provided in ``getRepository``. For example if I provide the name of Entity with this format ``AppBundle:MyEntity``, it works:

![pdt-ca-ok](https://user-images.githubusercontent.com/652505/31535544-bd55b110-affb-11e7-8459-0c927eb0cf81.png)

But if I provide the complete namespace as a string ``AppBundle\Entity\MyEntity`` (which must also be supported), I don't have any propositions in CA anymore:

![pdt-ca-empty](https://user-images.githubusercontent.com/652505/31535597-ed92fad6-affb-11e7-9ea4-e5c959cdea64.png)

If I provide the classname in other way ``MyEntity:class``, it partially works. You can notice that the custom method findAllForTransmission is not present in the list).

![pdt-ca-nok](https://user-images.githubusercontent.com/652505/31535718-5cfae1ea-affc-11e7-9ef1-ef035cdc20de.png)

It would be great to have the exact same result for this 3 cases.

**Comment by raziel057** [comment]
@zulus Is it a complicated to implement this feature? If you have no time to do it, would it be possible to provide me some information so that I can try to implement?

**Comment by zulus** [comment]
In theory pulse00/Doctrine-Eclipse-Plugin already have initial implementation. See https://github.com/pulse00/Doctrine-Eclipse-Plugin/blob/master/com.dubture.doctrine.core/src/com/dubture/doctrine/core/goals/evaluator/RepositoryGoalEvaluator.java

Current problems:

* During TypeInference PDT doesn't resolve ::class static into string, so getRepository(MyClass::class) will no work: https://bugs.eclipse.org/bugs/show_bug.cgi?id=470655
* It's not possible to collect Entity aliases (entity namespaces) in standard way or I didn't find it. There is an option to implement it via Symfony plugin by scaning container XML. In this case Doctrine plugin should share an API (and maybe in future also UI).

**Comment by raziel057** [comment]
@zulus First of all thanks for your answer and you work. Symfony and Doctrine plugins are very usefull.

The first issue seems to be resolved now, that's a good thing. For the second point, Doctrine plugin is currently able to scan a project to detect entities and propose entity alias (``AppBundle:MyEntity``), so I imagine it could be possible to also keep the namespace of referenced entities.

**Comment by zulus** [comment]
Yep, I merged patch from Michele Locati yesterday ;)

Next step is bug [459808](https://bugs.eclipse.org/bugs/show_bug.cgi?id=459808), [patch is already available](https://git.eclipse.org/r/#/c/111954/) , after that I'll prepare initial implementation for Symfony, later I'll prepare some kind of UI to add manually.

BTW, current namespace implementation is very limited. For example doesn't understand namespaces outside */Entity/* ;)

**Comment by raziel057** [comment]
Thanks you, it will be amazing!

**Comment by zulus** [comment]
Fixed by pulse00/Doctrine-Eclipse-Plugin#11

**Comment by zulus** [comment]
Build with fix is already available.

**Comment by raziel057** [comment]
Cool thank you I will try it and let you know.

**Comment by raziel057** [comment]
It works very well! It's a big improvement.

The only thing which remains (not really linked to this ticket) is that the returned object is not well detected. For example, I created a method in a specific Repository (Resource)

```php
public function getResourceById(int $id) : ?ResourceList
    {
        ...
        return $qb->getQuery()->getOneOrNullResult();
    }
```

```php
$resource = $em->getRepository(ResourceList::class)->getResourceById($id);
$resource->| // nothing is proposed here
```

I also tried to add DocBlock comment on ``getResourceById`` method but the problem remains.
